variables:
  AGENT_POOL_NAME_VAR: 'agl-automation-staging-ubuntu-1604-docker-18-06-1-ce-standard'
trigger:
- master
stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool: $(AGENT_POOL_NAME_VAR)
    steps:
    - script: echo Building!
    - task: AzureCLI@1
      inputs:
        azureSubscription: 'workspace-build-agent-containers'
        scriptLocation: 'inlineScript'
        inlineScript: 'ls -la'
- stage: Test
  jobs:
  - job: TestOnWindows
    pool: $(AGENT_POOL_NAME_VAR)
    steps:
    - script: echo Testing on Windows!
  - job: TestOnLinux
    pool: $(AGENT_POOL_NAME_VAR)
    steps:
    - script: echo Testing on Linux!
- stage: Deploy
  jobs:
  - job: Deploy
    pool: $(AGENT_POOL_NAME_VAR)
    steps:
    - script: echo Deploying the code!


# name: $(Date:yyyyMMdd)$(Rev:.r)
# variables:
#   var1: value1



# jobs:
# - job: One
#   steps:
#   - script: echo First step!
#   displayName: 'single line script'